### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by deepapargaonkar**
added a few points

### CODE REVIEW

**Review by deepapargaonkar — COMMENTED** [review]
Added few lines

**Review by NeetaPatke — CHANGES_REQUESTED** [review]
Please add the following points"
+ You can insert tables
+ You can insert images

**Review by NeetaPatke — APPROVED** [review]

**Review by deepapargaonkar — COMMENTED** [review]
Added two new points that were suggested by Neeta.

**Comment by deepapargaonkar** [comment]
Leave a comment

**Pull request closed without merging**
